# Generated by Django 2.2.4 on 2019-09-18 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_auto_20190917_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='adult',
            name='invalidreason',
            field=models.CharField(default='', max_length=1024, verbose_name='Reason(s) why record did not pass validation. (metadata)'),
        ),
        migrations.AddField(
            model_name='aggregateddata',
            name='invalidreason',
            field=models.CharField(default='', max_length=1024, verbose_name='Reason(s) why record did not pass validation. (metadata)'),
        ),
        migrations.AddField(
            model_name='child',
            name='invalidreason',
            field=models.CharField(default='', max_length=1024, verbose_name='Reason(s) why record did not pass validation. (metadata)'),
        ),
        migrations.AddField(
            model_name='closedperson',
            name='invalidreason',
            field=models.CharField(default='', max_length=1024, verbose_name='Reason(s) why record did not pass validation. (metadata)'),
        ),
        migrations.AddField(
            model_name='familiesbystratumdata',
            name='invalidreason',
            field=models.CharField(default='', max_length=1024, verbose_name='Reason(s) why record did not pass validation. (metadata)'),
        ),
        migrations.AddField(
            model_name='family',
            name='invalidreason',
            field=models.CharField(default='', max_length=1024, verbose_name='Reason(s) why record did not pass validation. (metadata)'),
        ),
    ]
